In [17]:
import pandas as pd
import numpy as np
import requests as req

In [18]:
nyse = pd.read_csv("Pricing Time Series 2.csv")

In [19]:
nyse.drop("Unnamed: 0", axis =1, inplace =True)
nyse

              Date Ticker    Volume  Weekly Close  Weekly Open
0       2018-01-22     PG   8460714         91.89        90.88
1       2018-01-19     PG  33702786         91.07        90.14
2       2018-01-12     PG  31208378         89.61        90.93
3       2018-01-05     PG  24952543         91.24        91.92
4       2017-12-29     PG  14920428         91.88        92.35
5       2017-12-22     PG  28806245         92.13        91.89
6       2017-12-15     PG  39115624         91.89        90.23
7       2017-12-08     PG  36743727         90.37        90.17
8       2017-12-01     PG  33444865         90.36        88.33
9       2017-11-24     PG  18821882         88.45        88.43
10      2017-11-17     PG  30839940         88.43        88.67
11      2017-11-10     PG  31365736         88.16        86.55
12      2017-11-03     PG  27389555         86.58        86.91
13      2017-10-27     PG  44504580         87.04        88.63
14      2017-10-20     PG  45074300         88.25        92.97
15      2017-10-13     PG  41254685         93.04        92.40
16      2017-10-06     PG  31365381         92.33        91.26
17      2017-09-29     PG  31605503         90.98        92.43
18      2017-09-22     PG  33812015         92.24        93.17
19      2017-09-15     PG  38463910         93.27        93.09
20      2017-09-08     PG  26809184         92.84        92.18
21      2017-09-01     PG  24437723         92.53        92.52
22      2017-08-25     PG  22615580         92.51        92.38
23      2017-08-18     PG  30662279         92.47        91.54
24      2017-08-11     PG  29484331         91.34        90.67
25      2017-08-04     PG  35039180         90.67        90.21
26      2017-07-28     PG  36939873         90.21        88.55
27      2017-07-21     PG  31466338         88.61        87.07
28      2017-07-14     PG  25277151         87.10        87.63
29      2017-07-07     PG  19378255         87.65        87.40
...            ...    ...       ...           ...          ...
416191  2010-09-10   GNRC    181100         13.36        13.07
416192  2010-09-03   GNRC    242600         13.09        12.43
416193  2010-08-27   GNRC    336100         12.51        12.65
416194  2010-08-20   GNRC    289600         12.58        12.65
416195  2010-08-13   GNRC    239800         12.76        14.57
416196  2010-08-06   GNRC    376900         14.47        15.17
416197  2010-07-30   GNRC    224600         14.77        15.19
416198  2010-07-23   GNRC    291200         15.07        14.45
416199  2010-07-16   GNRC    292600         14.38        14.97
416200  2010-07-09   GNRC    318100         15.01        14.44
416201  2010-07-02   GNRC    424600         14.27        15.03
416202  2010-06-25   GNRC   1040800         15.15        13.90
416203  2010-06-18   GNRC    685200         13.80        13.19
416204  2010-06-11   GNRC    315400         13.12        12.53
416205  2010-06-04   GNRC    365300         12.43        10.94
416206  2010-05-28   GNRC    875400         10.99        11.80
416207  2010-05-21   GNRC    770000         11.82        13.56
416208  2010-05-14   GNRC    908600         13.48        13.75
416209  2010-05-07   GNRC    535600         13.52        15.09
416210  2010-04-30   GNRC    415100         15.09        15.29
416211  2010-04-23   GNRC    329600         15.35        15.27
416212  2010-04-16   GNRC    609700         15.29        15.35
416213  2010-04-09   GNRC    396600         15.31        14.42
416214  2010-04-01   GNRC   2336900         14.30        13.51
416215  2010-03-26   GNRC    639900         14.75        15.24
416216  2010-03-19   GNRC   1114000         15.40        14.00
416217  2010-03-12   GNRC    414200         14.15        13.13
416218  2010-03-05   GNRC    329900         13.10        13.50
416219  2010-02-26   GNRC    601400         13.43        13.28
416220  2010-02-19   GNRC   1295200         13.23        13.40

[416221 rows x 5 columns]

In [20]:
date =[] 
open_price =[]
close_price = []
ticker = []
volume =[]

for index, row in nyse.iterrows():
    start = row["Weekly Open"]
    end = row["Weekly Close"]
    ten_perc = (start*.1)
    if((start-end)>=ten_perc):
        date.append(row["Date"])
        open_price.append(start)
        close_price.append(end)
        ticker.append(row["Ticker"])
        volume.append(row["Volume"])

In [21]:
df = pd.DataFrame({
    "Opening Price":open_price,
    "Closing Price":close_price,
    "Ticker":ticker,
    "Date":date
})
drops = df[["Ticker","Opening Price","Closing Price","Date"]]
drops

      Ticker  Opening Price  Closing Price        Date
0         PG        69.7700        59.5600  2008-10-10
1         PG        76.0000        68.2500  2000-11-03
2         PG        64.0000        57.0000  2000-06-09
3         PG        68.9400        59.7500  2000-04-28
4         PG        88.3800        53.7500  2000-03-10
5         PG       116.9000       102.7000  2000-01-21
6        MCC         7.6000         6.1900  2017-05-12
7        MCC         6.5600         5.5400  2016-02-12
8        MCC         7.1800         6.4600  2016-01-15
9        MCC        10.5800         8.8400  2014-12-12
10       KOF        73.9100        63.2100  2016-11-11
11       KOF       134.3300       120.0200  2013-08-30
12       KOF       145.0000       128.1000  2013-06-21
13       KOF        36.8700        32.6400  2009-02-20
14       KOF        45.3700        38.5600  2009-01-09
15       KOF        39.0000        28.1300  2008-10-24
16       KOF        46.6500        34.7500  2008-10-10
17       KOF        46.2000        41.0700  2007-08-03
18       KOF        21.0000        18.1700  2002-12-27
19       KOF        20.4500        17.8900  2001-10-12
20       KOF        20.1500        17.7000  2001-09-21
21       CPG         8.5500         7.5200  2017-11-17
22       CPG        15.4900        13.8800  2016-09-09
23       CPG        11.6300         9.7400  2016-01-08
24       CPG        13.0800        11.6700  2015-09-25
25       CPG        12.5100        10.1500  2015-08-21
26       CPG        17.2400        15.1800  2015-07-24
27       CPG        23.2000        18.8100  2014-12-12
28       CPG        32.8300        26.1900  2014-11-28
29       CPG        42.6894        36.9953  2011-09-23
...      ...            ...            ...         ...
10866    KOP        39.6300        32.4700  2014-11-07
10867    KOP        32.2000        28.4500  2011-11-25
10868    KOP        29.3000        24.1300  2011-09-23
10869    KOP        46.0800        41.1600  2011-05-06
10870    KOP        32.3000        27.9700  2010-05-21
10871    KOP        29.6200        26.1200  2009-10-30
10872    KOP        25.9000        22.6000  2009-07-10
10873    KOP        12.7200        10.1400  2009-03-06
10874    KOP        15.4200        13.3600  2009-02-27
10875    KOP        17.5000        15.2600  2009-02-20
10876    KOP        21.8900        18.1900  2008-12-26
10877    KOP        17.2700        14.0700  2008-11-21
10878    KOP        21.5200        17.9700  2008-11-14
10879    KOP        24.1000        21.0300  2008-11-07
10880    KOP        20.6900        17.5400  2008-10-24
10881    KOP        29.8700        20.0400  2008-10-10
10882    KOP        40.8800        30.5300  2008-10-03
10883    KOP        46.1300        41.3400  2008-09-26
10884    KOP        43.0400        36.4900  2007-11-16
10885    KOP        30.2400        27.0500  2007-07-27
10886    KOP        26.8530        24.0000  2007-03-02
10887   GNRC        35.0400        27.8900  2015-08-07
10888   GNRC        46.1800        40.0000  2015-05-01
10889   GNRC        45.4700        40.8600  2014-11-07
10890   GNRC        18.3400        15.5700  2011-09-23
10891   GNRC        18.7200        16.5200  2011-08-19
10892   GNRC        20.9300        18.5600  2011-05-06
10893   GNRC        14.5700        12.7600  2010-08-13
10894   GNRC        13.5600        11.8200  2010-05-21
10895   GNRC        15.0900        13.5200  2010-05-07

[10896 rows x 4 columns]

In [22]:
drops["Ticker"].count()

10896

In [23]:
drops.to_csv("price drop 2.csv", index=False)